docker: downgrade to ethtool<6.11

diff --git a/docker/bridge/Dockerfile b/docker/bridge/Dockerfile
--- a/docker/bridge/Dockerfile
+++ b/docker/bridge/Dockerfile
@@ -1,4 +1,11 @@
 FROM alpine:3.21
-RUN apk add --no-cache arping docker-cli ethtool iproute2 jq util-linux-misc
+
+# ethtool 6.11 is failing in '-X hkey' command on Linux kernel 6.1
+RUN <<EOF
+  set -euxo pipefail
+  echo 'https://dl-cdn.alpinelinux.org/alpine/v3.20/main' | tee -a /etc/apk/repositories
+  apk add --no-cache arping docker-cli 'ethtool<6.11' iproute2 jq util-linux-misc
+EOF
+
 ADD --chmod=755 https://github.com/jpetazzo/pipework/raw/9ba97f1735022fb5f811d9c2a304dda33fae1ad1/pipework /usr/local/bin/
 COPY --chmod=755 *.sh /usr/local/bin/
